version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: monthly
    time: "03:00"
    timezone: US/Central
  ignore:
  - dependency-name: nokogiri
    versions:
    - 1.11.0
